### ISSUE TITLE
Crashing issue with AE2 15.0.11 - pressing [G] on AE2 Sky Block

### ISSUE THREAD

**Issue by SirTwsted** [Spottedleaf/Starlight#196] opened 2023-09-21 15:54 UTC
When pressing [G]  on AE2 Sky Block to get AE2 internal database information.
The game crahes.

Minecraft v1.20.1
Forge v47.1.46
AE2 v15.0.11

Splash Screen Error 
`The game crashed whilst tesselating block model Error: java.lang.AbstractMethodError: Receiver class appeng.client.guidebook.scene.level.GuidebookLevel does not define or inherit an implementation of the resolved method 'abstract net.minecraft.world.level.chunk.ChunkAccess getAnyChunkImmediately(int, int)' of interface ca.spottedleaf.starlight.common.world.ExtendedWorld.`
Error Code [-1]

Here is the Pastebin Crash Report.
https://pastebin.com/mvD9hRTM

I have already notified AE2 developers, and I was informed to disable Starlight.
When I disabled Starlight, everything works again with AE2.
I used to have 79-fps with Starlight installed. Now I have 51 fps when starlight is disabled.

🤷‍♀️

**Comment by mindforger** [comment] 2023-09-21 16:13
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7415

**Comment by Spottedleaf** [comment] 2023-10-16 23:06
Duplicate of https://github.com/PaperMC/Starlight/issues/187

**Closed as completed by Spottedleaf** 2023-10-16 23:06 UTC
Labels: bug, duplicate, forge
