### ISSUE TITLE
[Forge 1.20.1] Crashing issue with Framed Blocks. (framedblocks.api.block.IFramedBlock.getLightEmission)

### ISSUE THREAD

**Issue by Gbergz** [Spottedleaf/Starlight#191] opened 2023-08-05 18:27 UTC
Title ^

### What happened: 
Getting crashes server side with Framed Blocks. Something with Light.

### Crash Report: 
https://gist.githubusercontent.com/Gbergz/1975bb412de6fe517afaa506cae98329/raw/bbf0286ce510821b7f7ee6ad4d4f92b503abf811/gistfile1.txt

### Versions:
**Starlight**: 1.1.2+forge.1cda73c
**MC**: 1.20.1
**Forge**: 47.1.3
**Framed Blocks**: 9.0.3

### Other info:
Fixed by removing Starlight as a temporary workaround.

**Comment by Spottedleaf** [comment] 2023-10-16 21:23
Duplicate of https://github.com/PaperMC/Starlight/issues/197

**Closed as completed by Spottedleaf** 2023-10-16 21:23 UTC
