### ISSUE TITLE
[Fabric]Issue with Release for 1.18.1

### ISSUE THREAD

**Issue by A-noximous** [Spottedleaf/Starlight#107] opened 2021-12-13 06:11 UTC
The 1.18.1 release of Starlight on [Modrinth](https://modrinth.com/mod/starlight), when installed on a server crashes the server with:
`java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))`

[Full crash log](https://github.com/PaperMC/Starlight/files/7701371/starlight-crash.log)

**Comment by DioEgizio** [comment] 2021-12-13 13:53
It's not an error, you need to update to java 17 for Minecraft 1.18.x to work...

**Comment by A-noximous** [comment] 2021-12-13 13:56
I do have java 17 installed, I have confirmed this with `java --version` Which returns:
```
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
```

**Comment by RealCamar** [comment] 2021-12-13 14:09
> I do have java 17 installed, I have confirmed this with `java --version` Which returns:
> 
> ```
> 
> openjdk 17.0.1 2021-10-19
> 
> OpenJDK Runtime Environment (build 17.0.1+12-39)
> 
> OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
> 
> ```
> 
> 

Check if your instance is actually using Java 17 with whatever launcher you're using

**Comment by CozzyBro2** [comment] 2021-12-13 17:15
I am able to reproduce this issue. Below is a log showing the installing the mod and then starting the server. 
```
gavin@arch ~> sudo pacmc install -a server "Starlight"
Searching for installable mods matching 'Starlight'

1) modrinth/Starlight (Fabric) [H8CaAYZC] by spottedleaf
  Rewrites the light engine to fix lighting performance and lighting errors
2) modrinth/Starlight (Forge) [iRfIGC1s] by spottedleaf
  Rewrites the light engine to fix lighting performance and lighting errors
3) curseforge/Starlight (Fabric) [521783] by Spottedstar
  Rewrites the light engine to fix lighting performance and lighting errors

Which mod do you want to install? (1, 2, 3) 1

Installing the mod at /srv/minecraft/mods

Downloading modrinth/Starlight (Fabric) Starlight 1.0.0 1.18.x
  [──────────────────────────────>] 100%

Successfully installed the given mod.
gavin@arch ~> minecraftd start
Starting server... failed
                                                                                                       i
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCaptureh.jar' nogui
[12:12:00] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.10
[12:12:01] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.10
[12:12:01] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
 - Mod 'Repurposed Structures' (repurposed_structures) 3.1.8+1.18.0 recommends version 1.0.0 or later of no_null_processors, which is missing!
	 - You should install version 1.0.0 or later of no_null_processors for the optimal experience.
[12:12:01] [main/INFO]: Loading 65 mods:
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.44
	- com_electronwill_night-config_core 3.6.4 via servercore-fabric
	- com_electronwill_night-config_toml 3.6.4 via servercore-fabric
	- com_typesafe_config 1.4.1 via confabricate
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- croptopia 1.7.2
	- fabric 0.43.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cd14 via fabric
	- fabric-api-lookup-api-v1 1.3.5+3ac43d9514 via fabric
	- fabric-biome-api-v1 6.0.1+3ac43d9514 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9514 via limitless
	- fabric-commands-v0 0.2.5+b4f4f6cd14 via fabric
	- fabric-containers-v0 0.1.18+d154e2c614 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d14 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9514 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957114 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a14 via fabric
	- fabric-events-interaction-v0 0.4.15+3ac43d9514 via fabric
	- fabric-events-lifecycle-v0 0.2.5+b4f4f6cd14 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9514 via fabric
	- fabric-item-api-v1 1.2.7+3ac43d9514 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9514 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33514 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9514 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9514 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd14 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9514 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd14 via fabric
	- fabric-object-builder-api-v1 1.10.13+3ac43d9514 via fabric
	- fabric-object-builders-v0 0.7.7+3ac43d9514 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac14 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via fabric-tpa
	- fabric-registry-sync-v0 0.8.5+3ac43d9514 via fabric
	- fabric-rendering-data-attachment-v1 0.3.3+d154e2c614 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9514 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via limitless
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9514 via fabric
	- fabric-structure-api-v1 2.0.8+295197a714 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9514 via limitless
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5514 via fabric
	- fabric-tpa 3.1.0
	- fabric-transfer-api-v1 1.5.4+b4f4f6cd14 via fabric
	- fabricloader 0.12.10
	- huntingham-hills 1.2.8 via limitless
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- java 17
	- kbootstrap 0.1.5 via limitless
	- krypton 0.1.6
	- limitless 1.5.13
	- minecraft 1.18.1
	- net_auoeke_extensions_asm-tree 0.37.0 via limitless
	- net_auoeke_extensions_extensions 0.37.0 via limitless
	- net_auoeke_reflect 3.2.0 via limitless
	- net_bytebuddy_byte-buddy-agent 1.12.3 via limitless
	- net_gudenau_lib_unsafe 1.6.1 via huntingham-hills
	- omega-config 1.0.8 via repurposed_structures
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- repurposed_structures 3.1.8+1.18.0
	- servercore-fabric 1.2.6-1.18.1
	- starlight 1.0.0+fabric.d0a3220
[12:12:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/srv/minecraft/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[12:12:02] [main/INFO]: Compatibility level set to JAVA_16
[12:12:02] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68) ~[fabric-server-launch.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: java.lang.RuntimeException: Error creating Mixin config starlight.mixins.json for mod starlight
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config starlight.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
no server running on /tmp/tmux-973/minecraft
gavin@arch ~ [1]>
```

This is my java version(s):
```
gavin@arch ~> archlinux-java status
Available Java environments:
  java-11-openjdk
  java-17-openjdk (default)
gavin@arch ~> java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12)
OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)
gavin@arch ~>
```
The crash only occurs when the latest starlight is present, removal shows the server starting as normal with other Java 17 requiring mods.

**Comment by electronicboy** [comment] 2021-12-13 17:22
> [12:12:02] [main/INFO]: Compatibility level set to JAVA_16 

outdated mixin?

**Comment by Chew** [comment] 2021-12-13 18:08
To be fair:

```
[04:42:51] [main/INFO]: Loading 42 mods:
...
	- fabricloader 0.12.11
	- fabrictailor 1.7.3
	- java 17
	- krypton 0.1.6
	- minecraft 1.18.1
	- starlight 1.0.0+fabric.d0a3220
```

I suppose ensure you can load up [the 1.18 version](https://cdn.modrinth.com/data/H8CaAYZC/versions/Starlight%201.0.0%201.18.x/starlight-1.0.0+fabric.d0a3220.jar)? I was able to run it fine with Java 17 in #106

**Comment by Spottedleaf** [comment] 2021-12-13 19:43
Duplicate of https://github.com/PaperMC/Starlight/issues/106

**Closed as completed by Spottedleaf** 2021-12-13 19:43 UTC
Labels: duplicate

**Comment by A-noximous** [comment] 2021-12-14 03:32
Can confirm updating installer and reinstalling the server jars fixed the issue. as per #106 .
