### ISSUE TITLE
Crash due to uninitialised nibble arrays during block light propagation

### ISSUE THREAD

**Issue by ghost** [Spottedleaf/Starlight#189] opened 2023-07-27 08:35 UTC
I Have No Idea Why My Game Crash When I Join Server It Is 1.20.1 And Updated From 1.19.2 Fabric 
[crash-2023-07-27_11.27.45-client.txt](https://github.com/PaperMC/Starlight/files/12181082/crash-2023-07-27_11.27.45-client.txt)
Here Is Mod List
![image](https://github.com/PaperMC/Starlight/assets/109978642/4075e834-2111-48c7-a2eb-b8e3bc7be28a)

**Comment by ghost** [comment] 2023-07-27 09:27
Problem Whit Starlight Prob Incompat

**Comment by CyanChanges** [comment] 2023-08-07 16:16
Same problem

**Comment by Spottedleaf** [comment] 2023-10-16 23:08
Duplicate of https://github.com/PaperMC/Starlight/issues/186

**Closed as completed by Spottedleaf** 2023-10-16 23:08 UTC
