### ISSUE TITLE
Crash when opening guide on some blocks

### ISSUE THREAD

**Issue by monstercatyy** [Spottedleaf/Starlight#207] opened 2024-01-02 17:16 UTC
### Crash Report Details:
Culprit: **A conflict between Applied Energistics 2's Guidebook and a lighting optimization mod (Starlight or Sodium).**
Trigger: **Rendering a chest block within the Guidebook.**
Root Cause: **Missing implementation of a method required for light calculation.**
Affected block: **Chest**
Affected screen: **Guidebook**

**Crash Log:** 
[crash-2024-01-03_00.59.49-client.txt](https://github.com/PaperMC/Starlight/files/13812311/crash-2024-01-03_00.59.49-client.txt)

Minecraft Version/Modloader: **1.20.1 Fabric**

**Comment by Spottedleaf** [comment] 2024-01-14 19:21
Duplicate of https://github.com/PaperMC/Starlight/issues/187

This is fixed in Starlight 1.1.3 (which is not available for 1.20.1)

**Closed as completed by Spottedleaf** 2024-01-14 19:21 UTC

**Comment by Weylend** [comment] 2024-02-09 21:47
Crashes me too
Is there a backport planned?
