### ISSUE TITLE
"Async chunk load took way too long" [Bug] [SP]

### ISSUE THREAD

**Issue by lAimBotl** [Spottedleaf/Starlight#206] opened 2023-12-28 19:23 UTC
I get a  "Async chunk load took way too long, this needs to be reported to the appropriate mod."
When trying to load a world, removing the mod lets me join the world,

Last thing I did was place a primitive alloy smelter down,
but I tried to recreate it in another world and nothing happened.

I did see "at com.enderio.machines.common.block.MachineBlock.getLightEmission"
and "at ca.spottedleaf.starlight.common.light.BlockStarLightEngine.calculateLightValue"

Here is the log (no crash, the world freezes until I close it with the task manager)
https://pastebin.com/PH9f0VbV

**Comment by SnowyOwlNugget** [comment] 2024-01-02 15:40
I seem to be having a similar issue with it, saying something about async took too long and something starlight chunk loading as well. also stops when I remove starlight. 
I didn't get a crash either
https://pastebin.com/RcEBB6yg

**Comment by Spottedleaf** [comment] 2024-01-14 13:48
Duplicate of https://github.com/PaperMC/Starlight/issues/197

**Closed as completed by Spottedleaf** 2024-01-14 13:48 UTC
Labels: bug, duplicate, forge
