### ISSUE TITLE
Vanilla Tweaks Warm Glow Compatibility

### ISSUE THREAD

**Issue by ghost** [Spottedleaf/Starlight#170] opened 2022-12-28 21:10 UTC
Allow Starlight to have compatibility with the Vanilla Tweaks Warm Glow texture pack and other lighting capabilities via resource packs.

**Comment by Timolino456** [comment] 2022-12-29 15:27
Duplicate of #153

**Closed as not planned** 2022-12-29 15:30 UTC
Labels: duplicate

**Comment by ghost** [comment] 2022-12-29 16:47
This should be reopened as the original issue has not had any updates.

**Comment by Timolino456** [comment] 2022-12-29 17:28
No, there is already an issue for it. If there are any updates, they will be added to the original issue. There is no use in making multiple issues for the same problem.

**Comment by ghost** [comment] 2022-12-29 19:42
I think that there hasn't been any progress on it, and although it isn't a huge deal, others like myself would love to see this feature added. I just felt as the original issue was ignored.
