### ISSUE TITLE
Worlds do not load/create

### ISSUE THREAD

**Issue by KorbynTalks** [Spottedleaf/Starlight#200] opened 2023-11-11 17:57 UTC
This is probably a compatibility issue because I have a dozen other mods.

If you wanna know what mods I use let me know

**Comment by toinouH** [comment] 2023-11-12 10:23
Without providing any logs or mod list we won't be able to help you ^^"

**Comment by bigtruckin78** [comment] 2023-11-14 23:08
Just experienced the same issue. I'm using Starlight in ATM 9. It was working fine up until last night. Then today the instance wouldn't load. I've attached what i think is the correct log. If not I can get something else. FWIW the last mod I was playing with was EnderIO.
[debug-2.log](https://github.com/PaperMC/Starlight/files/13358157/debug-2.log)

**Comment by ZestyBlaze** [comment] 2023-11-15 20:18
Yeah seems to be EnderIO's Flywheel Compat I think

**Comment by Spottedleaf** [comment] 2023-11-21 20:36
Duplicate of https://github.com/PaperMC/Starlight/issues/197

**Closed as completed by Spottedleaf** 2023-11-21 20:36 UTC
Labels: bug, forge
