### ISSUE TITLE
Conflict between the Create and Starlight

### ISSUE THREAD

**Issue by Marchlie** [Spottedleaf/Starlight#55] opened 2021-05-02 17:36 UTC
When using Create (Create v0.3.1c) and starlight (starlight v1.0.0-RC2) at the same time, the client will crash.
Simply disable the starlight mod to solve the problem.
For those that have also deployed Starlight on the server, it should not need to be disabled.

If you need any log or something.Please reply this issues.

**Comment by NebelNidas** [comment] 2021-05-06 12:47
Duplicate of #45.

**Comment by Spottedleaf** [comment] 2021-07-03 06:54
Duplicate of https://github.com/Tuinity/Starlight/issues/45

**Closed as completed by Spottedleaf** 2021-07-03 06:54 UTC
Labels: duplicate
