### ISSUE TITLE
[Crash] When opening guidebook from Applied Energistics 2 with StarLight installed

### ISSUE THREAD

**Issue by jarquafelmu** [Spottedleaf/Starlight#211] opened 2024-02-28 18:25 UTC
Linking to issue reported there so you are also aware https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7683

Not sure exactly which mod is causing this but a minecraft instance with just AE2 and this mod installed confirmed there is an interaction

**Comment by Mari023** [comment] 2024-02-28 18:38
duplicate of #187

**Closed as completed** 2024-03-08 12:16 UTC
