### ISSUE TITLE
No lighting when using bobby

### ISSUE THREAD

**Issue by ElliotS2007** [Spottedleaf/Starlight#58] opened 2021-05-13 09:56 UTC
No lighting in "ghost" or fake chunks when using bobby on a server or single-player world

![huge_2021-05-13_11 54 49_0000](https://user-images.githubusercontent.com/67877214/118109946-56290e00-b3d1-11eb-9993-8c88df2c715a.png)
(render distance set to 1 in bobby settings to better see the problem)

**Comment by jpenilla** [comment] 2021-05-13 10:01
duplicate of #38

**Comment by Spottedleaf** [comment] 2021-07-03 01:31
duplicate of #38

**Closed as completed by Spottedleaf** 2021-07-03 01:31 UTC
Labels: duplicate
