### ISSUE TITLE
 when minecraft have starlight and create in client，if player try make Mobile structure with create,client game will crash for this structure,its fine in server.

### ISSUE THREAD

**Issue by fkyah3** [Spottedleaf/Starlight#83] opened 2021-08-04 01:46 UTC
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 21-8-4 上午9:00
Description: Rendering entity in world

java.lang.AbstractMethodError: Method com/simibubi/create/foundation/utility/worldWrappers/chunk/WrappedChunk.getBlockEmptinessMap()[Z is abstract
	at com.simibubi.create.foundation.utility.worldWrappers.chunk.WrappedChunk.getBlockEmptinessMap(WrappedChunk.java) ~[?:mc1.16.5_v0.3.2b] {re:classloading}
	at ca.spottedleaf.starlight.common.light.BlockStarLightEngine.getEmptinessMap(BlockStarLightEngine.java:34) ~[?:1.0.0-RC2] {re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightEngine.setupCaches(StarLightEngine.java:204) ~[?:1.0.0-RC2] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:453) ~[?:1.0.0-RC2] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:469) ~[?:1.0.0-RC2] {re:mixin,re:classloading}
	at net.minecraft.world.lighting.WorldLightManager.func_215575_a(SourceFile:1104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:appliedenergistics2.mixins.json:feature.WorldLightManagerMixin,pl:mixin:APP:starlight.mixins.json:common.lightengine.WorldLightManagerMixin,pl:mixin:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.setupRenderWorld(ContraptionRenderDispatcher.java:209) ~[?:mc1.16.5_v0.3.2b] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.getRenderer(ContraptionRenderDispatcher.java:177) ~[?:mc1.16.5_v0.3.2b] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.render(ContraptionRenderDispatcher.java:159) ~[?:mc1.16.5_v0.3.2b] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer.render(ContraptionEntityRenderer.java:43) ~[?:mc1.16.5_v0.3.2b] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer.func_225623_a_(ContraptionEntityRenderer.java:13) ~[?:mc1.16.5_v0.3.2b] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:advancedrocketry:coremodmethod,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:advancedrocketry:coremodmethod,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-Forge%2036.2.2.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.simibubi.create.foundation.utility.worldWrappers.chunk.WrappedChunk.getBlockEmptinessMap(WrappedChunk.java) ~[?:mc1.16.5_v0.3.2b] {re:classloading}
	at ca.spottedleaf.starlight.common.light.BlockStarLightEngine.getEmptinessMap(BlockStarLightEngine.java:34) ~[?:1.0.0-RC2] {re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightEngine.setupCaches(StarLightEngine.java:204) ~[?:1.0.0-RC2] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:453) ~[?:1.0.0-RC2] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:469) ~[?:1.0.0-RC2] {re:mixin,re:classloading}
	at net.minecraft.world.lighting.WorldLightManager.func_215575_a(SourceFile:1104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:appliedenergistics2.mixins.json:feature.WorldLightManagerMixin,pl:mixin:APP:starlight.mixins.json:common.lightengine.WorldLightManagerMixin,pl:mixin:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.setupRenderWorld(ContraptionRenderDispatcher.java:209) ~[?:mc1.16.5_v0.3.2b] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.getRenderer(ContraptionRenderDispatcher.java:177) ~[?:mc1.16.5_v0.3.2b] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.render(ContraptionRenderDispatcher.java:159) ~[?:mc1.16.5_v0.3.2b] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer.render(ContraptionEntityRenderer.java:43) ~[?:mc1.16.5_v0.3.2b] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer.func_225623_a_(ContraptionEntityRenderer.java:13) ~[?:mc1.16.5_v0.3.2b] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: create:stationary_contraption (com.simibubi.create.content.contraptions.components.structureMovement.ControlledContraptionEntity)
	Entity ID: 1827
	Entity Name: 固定装置
	Entity's Exact location: 1246.00, 74.00, -801.00
	Entity's Block location: World: (1246,74,-801), Chunk: (at 14,4,15 in 77,-51; contains blocks 1232,0,-816 to 1247,255,-801), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer@46838166
	Location: 7.55,-49.85,-63.06 - World: (7,-50,-64), Chunk: (at 7,-4,0 in 0,-4; contains blocks 0,0,-64 to 15,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 0.0
	Delta: 0.38002014
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:advancedrocketry:coremodmethod,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,xf:fml:advancedrocketry:coremodmethod,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['fkyah3'/2120, l='ClientLevel', x=1238.45, y=122.24, z=-737.94]]
	Chunk stats: Client Chunk Cache: 361, 177
	Level dimension: minecraft:overworld
	Level spawn location: World: (1078,68,-467), Chunk: (at 6,4,13 in 67,-30; contains blocks 1072,0,-480 to 1087,255,-465), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Level time: 721831 game time, 745868 day time
	Server brand: LoliServer
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:client.world.ClientWorldMixin,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-Forge%2036.2.2.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1822323200 bytes (1737 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 12
	JVM Flags: 7 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+IgnoreUnrecognizedVMOptions -Xmn256m -Xmx3072m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.2
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		独眼巨人前置CyclopsCore-1.16.5-1.11.8.jar               |Cyclops Core                  |cyclopscore                   |1.11.8              |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |DONE      |Manifest: NOSIGNATURE
		Jade-1.16.4-2.7.1.jar                             |Jade                          |jade                          |2.7.1               |DONE      |Manifest: NOSIGNATURE
		前置女武神valkyrielib-1.16.5-3.0.9.2.jar               |ValkyrieLib                   |valkyrielib                   |1.16.5-3.0.9.2      |DONE      |Manifest: NOSIGNATURE
		火箭AdvancedRocketry-1.16.5-2.0.0-12-universal.jar  |Advanced Rocketry             |advancedrocketry              |1.16.5-2.0.0-12     |DONE      |Manifest: NOSIGNATURE
		jei.jar                                           |Just Enough Items             |jei                           |7.7.1.117           |DONE      |Manifest: NOSIGNATURE
		更流畅的加载smoothboot-forge-1.16.4-1.2.2.jar           |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		物品消失时间配置configurabledespawntimer_1.16.5-2.2.jar   |Configurable Despawn Timer    |configurabledespawntimer      |2.2                 |DONE      |Manifest: NOSIGNATURE
		词条自动转换autooredictconv-1.16.4-16.1.10.jar          |Auto Ore Dictionary Converter |autooredictconv               |16.1.10             |DONE      |Manifest: NOSIGNATURE
		spark-forge.jar                                   |spark                         |spark                         |1.6.0               |DONE      |Manifest: NOSIGNATURE
		ae2extras-1.3-1.16.5.jar                          |AE2 Extras                    |ae2extras                     |1.3-1.16.5          |DONE      |Manifest: NOSIGNATURE
		饰品栏curios-forge-1.16.5-4.0.5.2.jar                |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |Manifest: NOSIGNATURE
		幻梦eidolon-0.2.7.jar                               |Eidolon                       |eidolon                       |0.2.7               |DONE      |Manifest: NOSIGNATURE
		飞轮flywheel-1.16-0.1.1.jar                         |Flywheel                      |flywheel                      |1.16-0.1.1          |DONE      |Manifest: NOSIGNATURE
		前置库2InsaneLib-1.1.1-mc1.16.5.jar                  |InsaneLib                     |insanelib                     |1.1.1-mc1.16.5      |DONE      |Manifest: NOSIGNATURE
		invtweaks-1.16.2-1.0.0.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		机械动力.jar                                          |Create                        |create                        |v0.3.2b for 1.16.5  |DONE      |Manifest: NOSIGNATURE
		斯巴达盾SpartanShields-1.16.5-2.1.2.jar               |Spartan Shields               |spartanshields                |2.1.2               |DONE      |Manifest: NOSIGNATURE
		帕秋莉手册.jar                                         |Patchouli                     |patchouli                     |1.16.4-53.1         |DONE      |Manifest: NOSIGNATURE
		前置库collective-1.16.5-2.43.jar                     |Collective                    |collective                    |2.43                |DONE      |Manifest: NOSIGNATURE
		特殊aispecialai-1.16.5-1.0.1.jar                    |Special AI                    |specialai                     |1.16.5-1.0.1        |DONE      |Manifest: NOSIGNATURE
		前置飞碟citadel-1.7.2-1.16.5.jar                      |Citadel                       |citadel                       |1.7.2               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.11.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.11.1              |DONE      |Manifest: NOSIGNATURE
		中文汉化i18nupdatemod-1.16.5-2.0.2-hotfix-4.jar       |I18n update Mod               |i18nupdatemod                 |2.0.2               |DONE      |Manifest: NOSIGNATURE
		ae2appliedenergistics2-8.4.0.jar                  |Applied Energistics 2         |appliedenergistics2           |8.4.0               |DONE      |Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		邪恶工艺EvilCraft-1.16.5-1.1.6.jar                    |EvilCraft                     |evilcraft                     |1.1.6               |DONE      |Manifest: NOSIGNATURE
		简单发电机simplegens-1.16.5-3.0.9.0.jar                |Simple Generators             |simplegens                    |1.16.5-3.0.9.0      |DONE      |Manifest: NOSIGNATURE
		mdecore-1.16.4-16.1.0.jar                         |MattDahEpic Core              |mdecore                       |16.1.0              |DONE      |Manifest: NOSIGNATURE
		书架.jar                                            |Bookshelf                     |bookshelf                     |10.2.15             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		CrockPot-1.16.3-1.5.2-release.jar                 |Crock Pot                     |crockpot                      |1.5.2-release       |DONE      |Manifest: NOSIGNATURE
		星光starlight-forge-1.0.0-RC2-1.16.5.jar            |Starlight                     |starlight                     |1.0.0-RC2           |DONE      |Manifest: NOSIGNATURE
		斯巴达武器SpartanWeaponry-1.16.4-2.1.0-beta-4.jar      |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |DONE      |Manifest: NOSIGNATURE
		前置库3LibVulpes-1.16.5-1.0.2-25-universal.jar       |Lib Vulpes                    |libvulpes                     |1.16.5-1.0.2-25     |DONE      |Manifest: NOSIGNATURE
		菜单catalogue-1.3.0-1.16.5.jar                      |Catalogue                     |catalogue                     |1.3.0               |DONE      |Manifest: NOSIGNATURE
		背包宠物inventorypets-1.16.5-2.0.15.jar               |Inventory Pets                |inventorypets                 |2.0.15              |DONE      |Manifest: NOSIGNATURE
		魔改核心.jar                                          |CraftTweaker                  |crafttweaker                  |7.1.0.366           |DONE      |Manifest: NOSIGNATURE
		BotanyPots-1.16.5-7.0.17.jar                      |BotanyPots                    |botanypots                    |7.0.17              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		forge-1.16.5-36.2.2-universal.jar                 |Forge                         |forge                         |36.2.2              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		阿图姆Atum-1.16.5-2.2.6.jar                          |Atum 2                        |atum                          |1.16.5-2.2.6        |DONE      |Manifest: NOSIGNATURE
		暮色森林twilightforest-1.16.5-4.0.515-universal.jar   |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		资源包加载ResourcePackOrganizer-1.16.3-v1.2.0.jar      |Resource Pack Organizer       |resourcepackorganizer         |1.2.0               |DONE      |Manifest: NOSIGNATURE
		伤害配置altereddamage_1.16.5-1.5.jar                  |Altered Damage                |altereddamage                 |1.5                 |DONE      |Manifest: NOSIGNATURE
		地牢升起DungeonsArise-1.16.5-2.1.47-release.jar       |When Dungeons Arise           |dungeons_arise                |2.1.47              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 00525469-8209-49e7-8cf7-98a084c0164c
	Patchouli open book context: n/a
	Launched Version: 1.16.5-Forge 36.2.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 760/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.74, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/Minecraft-Mod-Language-Modpack-1-16.zip
	Current Language: 简体中文 (中国)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by jpenilla** [comment] 2021-08-04 01:48
Duplicate of https://github.com/Tuinity/Starlight/issues/45, incompatibility with create is a known issue.

**Closed as completed by jpenilla** 2021-08-04 01:48 UTC
Labels: duplicate
